### PR TITLE
Create combimatrix.py

### PR DESCRIPTION
**Pull request by shaurysrivastav27**
This code is helpful in finding all the possible combinations in a array which is commonly asked in cp.

### CODE REVIEW

**Comment by anktrj** [comment]
Hi you can convert this to a Sublime ext code snippet and make the PR.
For more info on Sublime Text code snippets refer https://www.freecodecamp.org/news/a-guide-to-preserving-your-wrists-with-sublime-text-snippets-7541662a53f2/

**Comment by shaurysrivastav27** [comment]
Sir i have converted the above code in the form of a snippet.

**Comment by anktrj** [comment]
Hi thanks @shaurysrivastav27. Looks good to me.
BTW you can call me Ankit

**Comment by shaurysrivastav27** [comment]
Thank you sir.

**Pull request merged**
